import { StyleSheet } from "react-native";
import {
  BorderRadius,
  Colors,
  Spacing,
  Typography,
} from "@/src/theme/designSystem";

const COLORS = {
  primary: Colors.primary,
  secondary: Colors.secondary,
  background: Colors.surface,
  cardBackground: Colors.surfaceCard,
  beigeLight: "#E7EFE4",
  textPrimary: Colors.text,
  textSecondary: Colors.textSecondary,
  chipBackground: "#D0E2CA",
  chipText: Colors.primary,
  divider: Colors.border,
  accentGreen: Colors.secondary,
  shadow: "#000000",
};

const SPACING = Spacing;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: SPACING.xl,
  },

  header: {
    backgroundColor: COLORS.primary,
    height: 116,
    borderBottomLeftRadius: BorderRadius.lg,
    borderBottomRightRadius: BorderRadius.lg,
  },

  avatarSection: {
    alignItems: "center",
    marginTop: -56,
    marginBottom: SPACING.sm,
  },
  avatarContainer: {
    position: "relative",
  },
  avatar: {
    width: 112,
    height: 112,
    borderRadius: 56,
    borderWidth: 4,
    borderColor: COLORS.cardBackground,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  editButton: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 44,
    height: 44,
    borderRadius: BorderRadius.full,
    backgroundColor: COLORS.secondary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: COLORS.cardBackground,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  editButtonText: {
    fontSize: Typography.body.fontSize,
    color: COLORS.cardBackground,
    fontWeight: "600",
  },

  nameSection: {
    alignItems: "center",
    marginBottom: SPACING.lg,
    paddingHorizontal: SPACING.md,
  },
  name: {
    fontSize: Typography.title.fontSize,
    fontWeight: Typography.title.fontWeight,
    color: COLORS.textPrimary,
    marginBottom: 2,
    letterSpacing: -0.5,
  },
  username: {
    fontSize: Typography.body.fontSize - 2,
    color: COLORS.textSecondary,
    marginBottom: SPACING.lg,
    fontWeight: "500",
  },

  levelCompactContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: SPACING.md,
    gap: SPACING.sm,
  },
  levelCompact: {
    backgroundColor: COLORS.beigeLight,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: BorderRadius.md,
  },
  levelCompactText: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.textPrimary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  badgeCompact: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: BorderRadius.md,
  },
  badgeCompactText: {
    fontSize: 10,
    fontWeight: "700",
    color: COLORS.cardBackground,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },

  privacyBadge: {
    backgroundColor: COLORS.chipBackground,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: BorderRadius.md,
  },
  privacyText: {
    fontSize: 11,
    color: COLORS.chipText,
    fontWeight: "600",
  },

  summaryStrip: {
    flexDirection: "row",
    backgroundColor: COLORS.cardBackground,
    borderRadius: BorderRadius.lg,
    marginHorizontal: SPACING.md,
    marginBottom: SPACING.lg,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.xs,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  summaryItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  summaryNumber: {
    fontSize: Typography.title.fontSize,
    fontWeight: "800",
    color: COLORS.primary,
    marginBottom: 2,
  },
  summaryLabel: {
    fontSize: 11,
    color: COLORS.textSecondary,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  summaryDivider: {
    width: 1,
    backgroundColor: COLORS.divider,
    marginHorizontal: SPACING.xs,
  },

  categoriesSection: {
    marginBottom: SPACING.lg,
  },
  categoriesScroll: {
    paddingHorizontal: SPACING.md,
    gap: SPACING.sm,
  },
  categoryChip: {
    backgroundColor: COLORS.chipBackground,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: BorderRadius.full,
    marginRight: SPACING.sm,
  },
  categoryText: {
    fontSize: 13,
    color: COLORS.chipText,
    fontWeight: "700",
    letterSpacing: 0.2,
  },

  bioCard: {
    backgroundColor: COLORS.beigeLight,
    borderRadius: BorderRadius.lg,
    padding: SPACING.md,
    marginHorizontal: SPACING.md,
    marginBottom: SPACING.lg,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
  },
  bioHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: SPACING.sm,
  },
  bioIcon: {
    fontSize: 18,
    marginRight: SPACING.sm,
  },
  bioTitle: {
    fontSize: Typography.body.fontSize - 2,
    fontWeight: "700",
    color: COLORS.textPrimary,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  bioText: {
    fontSize: Typography.body.fontSize - 2,
    color: COLORS.textSecondary,
    lineHeight: 21,
    textAlign: "left",
  },

  featuredPlantCard: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: BorderRadius.lg,
    padding: SPACING.md,
    marginHorizontal: SPACING.md,
    marginBottom: SPACING.lg,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  featuredPlantLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: SPACING.md,
  },
  featuredPlantContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  featuredPlantImageLarge: {
    width: 80,
    height: 80,
    borderRadius: BorderRadius.md,
    backgroundColor: COLORS.beigeLight,
    alignItems: "center",
    justifyContent: "center",
    marginRight: SPACING.md,
  },
  featuredPlantEmoji: {
    fontSize: 48,
  },
  featuredPlantInfo: {
    flex: 1,
  },
  featuredPlantName: {
    fontSize: Typography.body.fontSize + 4,
    fontWeight: "700",
    color: COLORS.textPrimary,
    marginBottom: 4,
    letterSpacing: -0.3,
  },
  featuredPlantSubtext: {
    fontSize: 13,
    color: COLORS.textSecondary,
    fontWeight: "500",
  },

  infoSection: {
    marginBottom: SPACING.lg,
    paddingHorizontal: SPACING.md,
    gap: SPACING.sm,
  },
  infoCard: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: BorderRadius.lg,
    padding: SPACING.md,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  infoLabel: {
    fontSize: 11,
    color: COLORS.textSecondary,
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    fontWeight: "700",
  },
  infoValue: {
    fontSize: Typography.body.fontSize - 1,
    fontWeight: "600",
    color: COLORS.textPrimary,
  },

  gardenSection: {
    marginBottom: SPACING.lg,
  },
  gardenHeader: {
    marginHorizontal: SPACING.md,
    marginBottom: SPACING.lg,
  },
  gardenHeaderLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: COLORS.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 4,
  },
  sectionTitle: {
    fontSize: Typography.title.fontSize - 2,
    fontWeight: "800",
    color: COLORS.textPrimary,
    letterSpacing: -0.5,
  },
  gardenGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: SPACING.md,
    gap: SPACING.sm,
  },
  gardenItem: {
    width: "31%",
    aspectRatio: 1,
  },
  gardenPlaceholder: {
    flex: 1,
    backgroundColor: COLORS.cardBackground,
    borderRadius: BorderRadius.md,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
    position: "relative",
  },
  gardenPlaceholderText: {
    fontSize: 32,
  },
  recentIndicator: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 18,
    height: 18,
    borderRadius: BorderRadius.full,
    backgroundColor: COLORS.accentGreen,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  recentIndicatorText: {
    fontSize: 12,
    color: COLORS.cardBackground,
    fontWeight: "900",
  },

  bottomSpacer: {
    height: SPACING.xl,
  },
});
