import { StyleSheet } from "react-native";

const COLORS = {
  primary: "#2F5D3A",
  secondary: "#6E8B5E",
  background: "#F4F2ED",
  cardBackground: "#FFFFFF",
  beigeLight: "#EDEAE4",
  textPrimary: "#1F2F22",
  textSecondary: "#6B7C6B",
  chipBackground: "#C8DBC4",
  chipText: "#2F5D3A",
  divider: "#E5E3DC",
  accentGreen: "#4A8159",
  shadow: "#000000",
};

const SPACING = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 40,
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: SPACING.xl,
  },

  header: {
    backgroundColor: COLORS.primary,
    height: 100,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
  },

  avatarSection: {
    alignItems: "center",
    marginTop: -50,
    marginBottom: SPACING.sm,
  },
  avatarContainer: {
    position: "relative",
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 5,
    borderColor: COLORS.cardBackground,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  editButton: {
    position: "absolute",
    bottom: 2,
    right: 2,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: COLORS.secondary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: COLORS.cardBackground,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  editButtonText: {
    fontSize: 13,
    color: COLORS.cardBackground,
    fontWeight: "600",
  },

  nameSection: {
    alignItems: "center",
    marginBottom: SPACING.md,
    paddingHorizontal: SPACING.md,
  },
  name: {
    fontSize: 26,
    fontWeight: "800",
    color: COLORS.textPrimary,
    marginBottom: 2,
    letterSpacing: -0.5,
  },
  username: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginBottom: SPACING.md,
    fontWeight: "500",
  },

  levelCompactContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: SPACING.sm,
    gap: SPACING.sm,
  },
  levelCompact: {
    backgroundColor: COLORS.beigeLight,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  levelCompactText: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.textPrimary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  badgeCompact: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  badgeCompactText: {
    fontSize: 10,
    fontWeight: "700",
    color: COLORS.cardBackground,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },

  privacyBadge: {
    backgroundColor: COLORS.chipBackground,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 14,
  },
  privacyText: {
    fontSize: 11,
    color: COLORS.chipText,
    fontWeight: "600",
  },

  summaryStrip: {
    flexDirection: "row",
    backgroundColor: COLORS.cardBackground,
    borderRadius: 20,
    marginHorizontal: SPACING.md,
    marginBottom: SPACING.md,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.xs,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  summaryItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  summaryNumber: {
    fontSize: 26,
    fontWeight: "800",
    color: COLORS.primary,
    marginBottom: 2,
  },
  summaryLabel: {
    fontSize: 11,
    color: COLORS.textSecondary,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  summaryDivider: {
    width: 1,
    backgroundColor: COLORS.divider,
    marginHorizontal: SPACING.xs,
  },

  categoriesSection: {
    marginBottom: SPACING.md,
  },
  categoriesScroll: {
    paddingHorizontal: SPACING.md,
    gap: SPACING.sm,
  },
  categoryChip: {
    backgroundColor: COLORS.chipBackground,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 24,
    marginRight: SPACING.sm,
  },
  categoryText: {
    fontSize: 13,
    color: COLORS.chipText,
    fontWeight: "700",
    letterSpacing: 0.2,
  },

  bioCard: {
    backgroundColor: COLORS.beigeLight,
    borderRadius: 20,
    padding: SPACING.md,
    marginHorizontal: SPACING.md,
    marginBottom: SPACING.md,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
  },
  bioHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: SPACING.sm,
  },
  bioIcon: {
    fontSize: 18,
    marginRight: SPACING.sm,
  },
  bioTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: COLORS.textPrimary,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  bioText: {
    fontSize: 14,
    color: COLORS.textSecondary,
    lineHeight: 21,
    textAlign: "left",
  },

  featuredPlantCard: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 20,
    padding: SPACING.md,
    marginHorizontal: SPACING.md,
    marginBottom: SPACING.md,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  featuredPlantLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: SPACING.md,
  },
  featuredPlantContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  featuredPlantImageLarge: {
    width: 80,
    height: 80,
    borderRadius: 16,
    backgroundColor: COLORS.beigeLight,
    alignItems: "center",
    justifyContent: "center",
    marginRight: SPACING.md,
  },
  featuredPlantEmoji: {
    fontSize: 48,
  },
  featuredPlantInfo: {
    flex: 1,
  },
  featuredPlantName: {
    fontSize: 20,
    fontWeight: "700",
    color: COLORS.textPrimary,
    marginBottom: 4,
    letterSpacing: -0.3,
  },
  featuredPlantSubtext: {
    fontSize: 13,
    color: COLORS.textSecondary,
    fontWeight: "500",
  },

  infoSection: {
    marginBottom: SPACING.md,
    paddingHorizontal: SPACING.md,
    gap: SPACING.sm,
  },
  infoCard: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 18,
    padding: SPACING.md,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  infoLabel: {
    fontSize: 11,
    color: COLORS.textSecondary,
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    fontWeight: "700",
  },
  infoValue: {
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.textPrimary,
  },

  gardenSection: {
    marginBottom: SPACING.md,
  },
  gardenHeader: {
    marginHorizontal: SPACING.md,
    marginBottom: SPACING.md,
  },
  gardenHeaderLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: COLORS.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 4,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: COLORS.textPrimary,
    letterSpacing: -0.5,
  },
  gardenGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: SPACING.md,
    gap: SPACING.sm,
  },
  gardenItem: {
    width: "31%",
    aspectRatio: 1,
  },
  gardenPlaceholder: {
    flex: 1,
    backgroundColor: COLORS.cardBackground,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
    position: "relative",
  },
  gardenPlaceholderText: {
    fontSize: 32,
  },
  recentIndicator: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: COLORS.accentGreen,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  recentIndicatorText: {
    fontSize: 12,
    color: COLORS.cardBackground,
    fontWeight: "900",
  },

  bottomSpacer: {
    height: SPACING.lg,
  },
});
